### PR TITLE
Prettier Formatting & Eval thing idek

### PR DESCRIPTION
**Pull request by tandpfun**
yes

### CODE REVIEW

**Review by GamingGeek — CHANGES_REQUESTED** [review]
package-lock.json should be removed, yarn is superior

**Comment by GamingGeek** [comment]
I can't even tell what the actual changes are since you flooded it with prettier changes lol

I think it would be better if the prettier changes were separate

**Comment by tandpfun** [comment]
prettier changes r seprate, only code change I made was to eval

**Comment by GamingGeek** [comment]
> prettier changes r seprate, only code change I made was to eval

I meant that they should either be a separate pr or just not included at all

**Comment by tandpfun** [comment]
oh ok, so u close this and i redo it

**Pull request closed without merging**
